"""video table

Revision ID: d125a6a55a35
Revises: 
Create Date: 2024-01-27 13:37:28.896572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd125a6a55a35'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('thumbnail', sa.String(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_video_channel'), ['channel'], unique=False)
        batch_op.create_index(batch_op.f('ix_video_title'), ['title'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_video_title'))
        batch_op.drop_index(batch_op.f('ix_video_channel'))

    op.drop_table('video')
    # ### end Alembic commands ###
